WITH RAW_PRESIDENT AS (
	SELECT SPRIDEN_LAST_NAME, 
		SPRIDEN_MI, 
		SPRIDEN_FIRST_NAME, 
		SPRIDEN_ID, 
		NBRJOBS.*, 
		NBRBJOB.* 
	FROM NBRJOBS
    INNER JOIN NBRBJOB
        ON NBRBJOB_PIDM = NBRJOBS_PIDM
        AND NBRBJOB_POSN = NBRJOBS_POSN
		AND NBRBJOB_CONTRACT_TYPE = 'P'
		AND (NBRBJOB_BEGIN_DATE <= SYSDATE 
			AND (NBRBJOB_END_DATE > SYSDATE 
				OR NBRBJOB_END_DATE IS NULL))
    INNER JOIN SPRIDEN
        ON SPRIDEN_PIDM = NBRJOBS_PIDM
        AND SPRIDEN_CHANGE_IND IS NULL
    INNER JOIN PEBEMPL
        ON PEBEMPL_PIDM = NBRJOBS_PIDM
        AND PEBEMPL_EMPL_STATUS <> 'T'
        AND PEBEMPL_INTERNAL_FT_PT_IND <> 'P'
    WHERE NBRJOBS_STATUS = 'A'
    AND NBRJOBS_EFFECTIVE_DATE <= SYSDATE
	AND NBRJOBS_ECLS_CODE NOT IN ('E2','F3','H2','H4','N2','R0','R2','R4','R6')
    AND NBRJOBS_ORGN_CODE_TS NOT IN ('11001','11021','20023','20026','22129','22226','24209',
            '25008','25914','26050','26414','26510','29002','29003','29007','29011','29012',
            '29013','29304','29310','29311','30204','30205','30206','30209','30210','30212',
            '30232','30249','30251','30254','30257','30258','30501','30601','40017','52002',
            '52005','52006','52109','52201','52302','52303','53110','53701','54011','80010',
            '90011','90012','90016','95102','95113','95401','95601','96021','96031','96041',
            '96051','96061','97021','97031','97041','97051','97061','97071','97081','97091','97101')
    AND UPPER(NBRJOBS_DESC) NOT LIKE '%ADJUNCT%' 
    AND UPPER(NBRJOBS_DESC) NOT LIKE '%ADJCT%'
    AND UPPER(NBRJOBS_DESC) NOT LIKE '%ASST%'
	AND (UPPER(NBRJOBS_DESC) LIKE '%PRESIDENT%')
	AND NBRJOBS_EFFECTIVE_DATE = 
        (SELECT MAX(A.NBRJOBS_EFFECTIVE_DATE) 
            FROM NBRJOBS A 
            WHERE A.NBRJOBS_PIDM = NBRJOBS_PIDM 
            AND A.NBRJOBS_SUFF = NBRJOBS_SUFF 
            AND A.NBRJOBS_POSN = NBRJOBS_POSN
            AND A.NBRJOBS_STATUS = 'A'
            AND UPPER(A.NBRJOBS_DESC) LIKE 'PRESIDENT'
        )
),
PRESIDENT AS (
    SELECT 'PRESIDENT' TITLE, RAW_PRESIDENT.* FROM RAW_PRESIDENT
    WHERE RAW_PRESIDENT.NBRJOBS_EFFECTIVE_DATE = (SELECT MAX(NBRJOBS_EFFECTIVE_DATE) FROM RAW_PRESIDENT A
                                                    WHERE RAW_PRESIDENT.NBRJOBS_PIDM = A.NBRJOBS_PIDM
                                                    AND RAW_PRESIDENT.NBRJOBS_POSN = A.NBRJOBS_POSN)
),
RAW_VP AS (
	SELECT SPRIDEN_LAST_NAME, 
		SPRIDEN_MI, 
		SPRIDEN_FIRST_NAME, 
		SPRIDEN_ID, 
		NBRJOBS.*, 
		NBRBJOB.* 
	FROM NBRJOBS
    INNER JOIN NBRBJOB
        ON NBRBJOB_PIDM = NBRJOBS_PIDM
        AND NBRBJOB_POSN = NBRJOBS_POSN
		AND (NBRBJOB_BEGIN_DATE <= SYSDATE 
			AND (NBRBJOB_END_DATE > SYSDATE 
				OR NBRBJOB_END_DATE IS NULL))
    INNER JOIN SPRIDEN
        ON SPRIDEN_PIDM = NBRJOBS_PIDM
        AND SPRIDEN_CHANGE_IND IS NULL
    INNER JOIN PEBEMPL
        ON PEBEMPL_PIDM = NBRJOBS_PIDM
        AND PEBEMPL_EMPL_STATUS <> 'T'
        AND PEBEMPL_INTERNAL_FT_PT_IND <> 'P'
    WHERE NBRJOBS_STATUS = 'A'
    AND NBRBJOB_CONTRACT_TYPE = 'P'
    AND (NBRBJOB_BEGIN_DATE <= SYSDATE AND (NBRBJOB_END_DATE > SYSDATE OR NBRBJOB_END_DATE IS NULL))
    AND NBRJOBS_STATUS = 'A'
    AND NBRJOBS_EFFECTIVE_DATE <= SYSDATE
	AND NBRJOBS_ECLS_CODE NOT IN ('E2','F3','H2','H4','N2','R0','R2','R4','R6')
    AND NBRJOBS_ORGN_CODE_TS NOT IN ('11001','11021','20023','20026','22129','22226','24209',
            '25008','25914','26050','26414','26510','29002','29003','29007','29011','29012',
            '29013','29304','29310','29311','30204','30205','30206','30209','30210','30212',
            '30232','30249','30251','30254','30257','30258','30501','30601','40017','52002',
            '52005','52006','52109','52201','52302','52303','53110','53701','54011','80010',
            '90011','90012','90016','95102','95113','95401','95601','96021','96031','96041',
            '96051','96061','97021','97031','97041','97051','97061','97071','97081','97091','97101')
    AND (UPPER(NBRJOBS_DESC) LIKE '%VP%' 
        OR UPPER(NBRJOBS_DESC) LIKE '%VICE PRESIDENT%' 
        OR UPPER(NBRJOBS_DESC) LIKE '%EXEC ASST%'
        OR UPPER(NBRJOBS_DESC) LIKE '%ASST TO DEAN STDNTS%')
    AND UPPER(NBRJOBS_DESC) NOT LIKE '%GRAD ASST%'
    AND UPPER(NBRJOBS_DESC) NOT LIKE '%EXEC ASST TO PROVOST%'
    AND UPPER(NBRJOBS_DESC) NOT LIKE '%ASSC%'
),
VP AS (
    SELECT 'VICE_PRESIDENT' TITLE, RAW_VP.* FROM RAW_VP
    WHERE RAW_VP.NBRJOBS_EFFECTIVE_DATE = (SELECT MAX(NBRJOBS_EFFECTIVE_DATE) FROM RAW_VP A
                                                WHERE RAW_VP.NBRJOBS_PIDM = A.NBRJOBS_PIDM
                                                AND RAW_VP.NBRJOBS_POSN = A.NBRJOBS_POSN)
),
RAW_PROVOST AS (
	SELECT SPRIDEN_LAST_NAME, 
		SPRIDEN_MI, 
		SPRIDEN_FIRST_NAME, 
		SPRIDEN_ID, 
		NBRJOBS.*, 
		NBRBJOB.* 
	FROM NBRJOBS
    INNER JOIN NBRBJOB
        ON NBRBJOB_PIDM = NBRJOBS_PIDM
        AND NBRBJOB_POSN = NBRJOBS_POSN
		AND (NBRBJOB_BEGIN_DATE <= SYSDATE 
			AND (NBRBJOB_END_DATE > SYSDATE 
				OR NBRBJOB_END_DATE IS NULL))
    INNER JOIN SPRIDEN
        ON SPRIDEN_PIDM = NBRJOBS_PIDM
        AND SPRIDEN_CHANGE_IND IS NULL
    INNER JOIN PEBEMPL
        ON PEBEMPL_PIDM = NBRJOBS_PIDM
        AND PEBEMPL_EMPL_STATUS <> 'T'
        AND PEBEMPL_INTERNAL_FT_PT_IND <> 'P'
    WHERE NBRJOBS_STATUS = 'A'
    AND NBRBJOB_CONTRACT_TYPE = 'P'
    AND (NBRBJOB_BEGIN_DATE <= SYSDATE AND (NBRBJOB_END_DATE > SYSDATE OR NBRBJOB_END_DATE IS NULL))
    AND NBRJOBS_STATUS = 'A'
    AND NBRJOBS_EFFECTIVE_DATE <= SYSDATE
	AND NBRJOBS_ECLS_CODE NOT IN ('E2','F3','H2','H4','N2','R0','R2','R4','R6')
    AND NBRJOBS_ORGN_CODE_TS NOT IN ('11001','11021','20023','20026','22129','22226','24209',
            '25008','25914','26050','26414','26510','29002','29003','29007','29011','29012',
            '29013','29304','29310','29311','30204','30205','30206','30209','30210','30212',
            '30232','30249','30251','30254','30257','30258','30501','30601','40017','52002',
            '52005','52006','52109','52201','52302','52303','53110','53701','54011','80010',
            '90011','90012','90016','95102','95113','95401','95601','96021','96031','96041',
            '96051','96061','97021','97031','97041','97051','97061','97071','97081','97091','97101')
    AND UPPER(NBRJOBS_DESC) NOT LIKE '%ADJUNCT%' 
    AND UPPER(NBRJOBS_DESC) NOT LIKE '%ADJCT%'
	AND (UPPER(NBRJOBS_DESC) LIKE '%PROVOST%' OR UPPER(NBRJOBS_DESC) LIKE '%EXEC ASST%PROVOST%')
    AND UPPER(NBRJOBS_DESC) NOT LIKE '%STUDENT%'
    AND UPPER(NBRJOBS_DESC) NOT LIKE '%PROVOST EXEC VP%'
),
PROVOST AS (
    SELECT 'PROVOST' TITLE, RAW_PROVOST.* FROM RAW_PROVOST
    WHERE RAW_PROVOST.NBRJOBS_EFFECTIVE_DATE = (SELECT MAX(NBRJOBS_EFFECTIVE_DATE) FROM RAW_PROVOST A
                                                WHERE RAW_PROVOST.NBRJOBS_PIDM = A.NBRJOBS_PIDM
                                                AND RAW_PROVOST.NBRJOBS_POSN = A.NBRJOBS_POSN)
),
RAW_DIRECTORS AS (
    SELECT SPRIDEN_LAST_NAME, SPRIDEN_MI, SPRIDEN_FIRST_NAME, SPRIDEN_ID, NBRJOBS.*, NBRBJOB.*
    FROM NBRJOBS
    INNER JOIN NBRBJOB
        ON NBRBJOB_PIDM = NBRJOBS_PIDM
        AND NBRBJOB_POSN = NBRJOBS_POSN
		AND (NBRBJOB_BEGIN_DATE <= SYSDATE 
			AND (NBRBJOB_END_DATE > SYSDATE 
				OR NBRBJOB_END_DATE IS NULL))
    INNER JOIN SPRIDEN
        ON SPRIDEN_PIDM = NBRJOBS_PIDM
        AND SPRIDEN_CHANGE_IND IS NULL
    INNER JOIN PEBEMPL
        ON PEBEMPL_PIDM = NBRJOBS_PIDM
        AND PEBEMPL_EMPL_STATUS <> 'T'
        AND PEBEMPL_INTERNAL_FT_PT_IND <> 'P'
    WHERE NBRJOBS_STATUS = 'A'
	AND NBRJOBS_EFFECTIVE_DATE <= SYSDATE
	AND NBRJOBS_ECLS_CODE NOT IN ('E2','F3','H2','H4','N2','R0','R2','R4','R6')
    AND NBRJOBS_ORGN_CODE_TS NOT IN ('11001','11021','20023','20026','22129','22226','24209',
            '25008','25914','26050','26414','26510','29002','29003','29007','29011','29012',
            '29013','29304','29310','29311','30204','30205','30206','30209','30210','30212',
            '30232','30249','30251','30254','30257','30258','30501','30601','40017','52002',
            '52005','52006','52109','52201','52302','52303','53110','53701','54011','80010',
            '90011','90012','90016','95102','95113','95401','95601','96021','96031','96041',
            '96051','96061','97021','97031','97041','97051','97061','97071','97081','97091','97101')
    AND UPPER(NBRJOBS_DESC) NOT LIKE '%ADJUNCT%' 
    AND UPPER(NBRJOBS_DESC) NOT LIKE '%ADJCT%'
    AND (UPPER(NBRJOBS_DESC) NOT LIKE '%ASST%')
	AND ((UPPER(NBRJOBS_DESC) LIKE '%DIR/PROFESSOR%')
        OR (UPPER(NBRJOBS_DESC) LIKE 'DIR/ASSC PROFESSOR')
        OR (UPPER(NBRJOBS_DESC) LIKE '%EXEC DIR ENRLMNT%')
        OR (UPPER(NBRJOBS_DESC) LIKE '%OFFCR CHIEF DIVERSITY%')
        OR (UPPER(NBRJOBS_DESC) LIKE 'DIR ATH'))
),
DIRECTORS AS (
    SELECT 'DIRECTORS' AS TITLE, RAW_DIRECTORS.* FROM RAW_DIRECTORS
    WHERE RAW_DIRECTORS.NBRJOBS_EFFECTIVE_DATE = (SELECT MAX(NBRJOBS_EFFECTIVE_DATE) 
                                                        FROM RAW_DIRECTORS A 
                                                        WHERE A.NBRJOBS_PIDM = RAW_DIRECTORS.NBRJOBS_PIDM
                                                            AND A.NBRJOBS_POSN = RAW_DIRECTORS.NBRJOBS_POSN
                                               )
    AND RAW_DIRECTORS.NBRJOBS_SGRP_CODE = (SELECT MAX(NBRJOBS_SGRP_CODE) 
                                                        FROM RAW_DIRECTORS A 
                                                        WHERE A.NBRJOBS_PIDM = RAW_DIRECTORS.NBRJOBS_PIDM
                                                            AND A.NBRJOBS_POSN = RAW_DIRECTORS.NBRJOBS_POSN
                                               )
    AND RAW_DIRECTORS.NBRBJOB_BEGIN_DATE = (SELECT MAX(NBRBJOB_BEGIN_DATE)
                                            FROM NBRBJOB A
                                            WHERE A.NBRBJOB_PIDM = RAW_DIRECTORS.NBRBJOB_PIDM
                                            AND A.NBRBJOB_POSN = RAW_DIRECTORS.NBRBJOB_POSN
                                            AND A.NBRBJOB_CONTRACT_TYPE = RAW_DIRECTORS.NBRBJOB_CONTRACT_TYPE)
),
RAW_ACADEMIC_SU AS (
    --NOW INCLUDES THE CODE FOR THE INTERIM CHAIRS AS WELL
    SELECT SPRIDEN_LAST_NAME, SPRIDEN_MI, SPRIDEN_FIRST_NAME, SPRIDEN_ID, NBRJOBS.*, NBRBJOB.*
    FROM NBRJOBS
    INNER JOIN NBRBJOB
        ON NBRBJOB_PIDM = NBRJOBS_PIDM
        AND NBRBJOB_POSN = NBRJOBS_POSN
		AND NBRBJOB_CONTRACT_TYPE = 'P'
		AND (NBRBJOB_BEGIN_DATE <= SYSDATE 
			AND (NBRBJOB_END_DATE > SYSDATE 
				OR NBRBJOB_END_DATE IS NULL))
    INNER JOIN SPRIDEN
        ON SPRIDEN_PIDM = NBRJOBS_PIDM
        AND SPRIDEN_CHANGE_IND IS NULL
    INNER JOIN PEBEMPL
        ON PEBEMPL_PIDM = NBRJOBS_PIDM
        AND PEBEMPL_EMPL_STATUS <> 'T'
        AND PEBEMPL_INTERNAL_FT_PT_IND <> 'P'
    WHERE NBRJOBS_STATUS = 'A'
	AND NBRJOBS_EFFECTIVE_DATE <= SYSDATE
	AND NBRJOBS_ECLS_CODE NOT IN ('E2','F3','H2','H4','N2','R0','R2','R4','R6')
    AND NBRJOBS_ORGN_CODE_TS NOT IN ('11001','11021','20023','20026','22129','22226','24209',
            '25008','25914','26050','26414','26510','29002','29003','29007','29011','29012',
            '29013','29304','29310','29311','30204','30205','30206','30209','30210','30212',
            '30232','30249','30251','30254','30257','30258','30501','30601','40017','52002',
            '52005','52006','52109','52201','52302','52303','53110','53701','54011','80010',
            '90011','90012','90016','95102','95113','95401','95601','96021','96031','96041',
            '96051','96061','97021','97031','97041','97051','97061','97071','97081','97091','97101')
    AND UPPER(NBRJOBS_DESC) NOT LIKE '%ADJUNCT%' 
    AND UPPER(NBRJOBS_DESC) NOT LIKE '%ADJCT%'
    AND (UPPER(NBRJOBS_DESC) NOT LIKE '%ASST%')
	AND (UPPER(NBRJOBS_DESC) LIKE '%CHAIR%' OR UPPER(NBRJOBS_DESC) LIKE '%DEAN%' OR UPPER(NBRJOBS_DESC) LIKE '%INTERIM CHAIR%')
),
ACADEMIC_SU AS (
    SELECT 'DEANS/CHAIRS' TITLE, RAW_ACADEMIC_SU.* FROM RAW_ACADEMIC_SU
    WHERE RAW_ACADEMIC_SU.NBRJOBS_EFFECTIVE_DATE = (SELECT MAX(NBRJOBS_EFFECTIVE_DATE) 
                                                    FROM RAW_ACADEMIC_SU A 
                                                    WHERE A.NBRJOBS_PIDM = RAW_ACADEMIC_SU.NBRJOBS_PIDM 
                                                    AND A.NBRJOBS_POSN = RAW_ACADEMIC_SU.NBRJOBS_POSN)
),
RAW_FACULTY AS (
    SELECT SPRIDEN_LAST_NAME, SPRIDEN_MI, SPRIDEN_FIRST_NAME, SPRIDEN_ID, NBRJOBS.*, NBRBJOB.*
    FROM NBRJOBS
    INNER JOIN NBRBJOB
        ON NBRBJOB_PIDM = NBRJOBS_PIDM
        AND NBRBJOB_POSN = NBRJOBS_POSN
		AND NBRBJOB_CONTRACT_TYPE = 'P'
		AND (NBRBJOB_BEGIN_DATE <= SYSDATE 
			AND (NBRBJOB_END_DATE > SYSDATE 
				OR NBRBJOB_END_DATE IS NULL))
    INNER JOIN SPRIDEN
        ON SPRIDEN_PIDM = NBRJOBS_PIDM
        AND SPRIDEN_CHANGE_IND IS NULL
    INNER JOIN PEBEMPL
        ON PEBEMPL_PIDM = NBRJOBS_PIDM
        AND PEBEMPL_EMPL_STATUS <> 'T'
        AND PEBEMPL_INTERNAL_FT_PT_IND <> 'P'
    WHERE NBRJOBS_STATUS = 'A'
	AND NBRJOBS_EFFECTIVE_DATE <= SYSDATE
	AND NBRJOBS_ECLS_CODE NOT IN ('E2','F3','H2','H4','N2','R0','R2','R4','R6')
    AND NBRJOBS_ORGN_CODE_TS NOT IN ('11001','11021','20023','20026','22129','22226','24209',
            '25008','25914','26050','26414','26510','29002','29003','29007','29011','29012',
            '29013','29304','29310','29311','30204','30205','30206','30209','30210','30212',
            '30232','30249','30251','30254','30257','30258','30501','30601','40017','52002',
            '52005','52006','52109','52201','52302','52303','53110','53701','54011','80010',
            '90011','90012','90016','95102','95113','95401','95601','96021','96031','96041',
            '96051','96061','97021','97031','97041','97051','97061','97071','97081','97091','97101')
	AND NBRJOBS_POSN LIKE 'F%'
    AND UPPER(NBRJOBS_DESC) NOT LIKE '%ADJUNCT%' 
    AND UPPER(NBRJOBS_DESC) NOT LIKE '%ADJCT%'
),
FACULTY AS (
    SELECT 'FACULTY' AS TITLE, RAW_FACULTY.* FROM RAW_FACULTY
    WHERE RAW_FACULTY.NBRJOBS_EFFECTIVE_DATE = (SELECT MAX(NBRJOBS_EFFECTIVE_DATE) 
                                                FROM RAW_FACULTY A 
                                                WHERE A.NBRJOBS_PIDM = RAW_FACULTY.NBRJOBS_PIDM 
                                                AND A.NBRJOBS_POSN = RAW_FACULTY.NBRJOBS_POSN)
),
RAW_EMPLOYEE AS (
    SELECT SPRIDEN_LAST_NAME, SPRIDEN_MI, SPRIDEN_FIRST_NAME, SPRIDEN_ID, NBRJOBS.*, NBRBJOB.*
    FROM NBRJOBS
    INNER JOIN NBRBJOB
        ON NBRBJOB_PIDM = NBRJOBS_PIDM
        AND NBRBJOB_POSN = NBRJOBS_POSN
		AND NBRBJOB_CONTRACT_TYPE = 'P'
		AND (NBRBJOB_BEGIN_DATE <= SYSDATE 
			AND (NBRBJOB_END_DATE > SYSDATE 
				OR NBRBJOB_END_DATE IS NULL))
    INNER JOIN SPRIDEN
        ON SPRIDEN_PIDM = NBRJOBS_PIDM
        AND SPRIDEN_CHANGE_IND IS NULL
    INNER JOIN PEBEMPL
        ON PEBEMPL_PIDM = NBRJOBS_PIDM
        AND PEBEMPL_EMPL_STATUS <> 'T'
        AND PEBEMPL_INTERNAL_FT_PT_IND <> 'P'
    WHERE NBRJOBS_STATUS = 'A'
	AND NBRJOBS_EFFECTIVE_DATE <= SYSDATE
	AND NBRJOBS_ECLS_CODE NOT IN ('E2','F3','H2','H4','N2','R0','R2','R4','R6')
    AND NBRJOBS_ORGN_CODE_TS NOT IN ('11001','11021','20023','20026','22129','22226','24209',
            '25008','25914','26050','26414','26510','29002','29003','29007','29011','29012',
            '29013','29304','29310','29311','30204','30205','30206','30209','30210','30212',
            '30232','30249','30251','30254','30257','30258','30501','30601','40017','52002',
            '52005','52006','52109','52201','52302','52303','53110','53701','54011','80010',
            '90011','90012','90016','95102','95113','95401','95601','96021','96031','96041',
            '96051','96061','97021','97031','97041','97051','97061','97071','97081','97091','97101') 
	AND NBRJOBS_POSN LIKE 'E%'
    AND UPPER(NBRJOBS_DESC) NOT LIKE '%ADJUNCT%' 
    AND UPPER(NBRJOBS_DESC) NOT LIKE '%ADJCT%'
),
EMPLOYEE AS (
    SELECT 'EMPLOYEE' AS TITLE, RAW_EMPLOYEE.* FROM RAW_EMPLOYEE
    WHERE RAW_EMPLOYEE.NBRJOBS_EFFECTIVE_DATE = (SELECT MAX(NBRJOBS_EFFECTIVE_DATE) 
                                                    FROM RAW_EMPLOYEE A 
                                                    WHERE A.NBRJOBS_PIDM = RAW_EMPLOYEE.NBRJOBS_PIDM
                                                    AND A.NBRJOBS_POSN = RAW_EMPLOYEE.NBRJOBS_POSN)
),
RAW_EXECUTIVE_ASSISTANTS AS (
    SELECT SPRIDEN_LAST_NAME, SPRIDEN_MI, SPRIDEN_FIRST_NAME, SPRIDEN_ID, NBRJOBS.*, NBRBJOB.* FROM NBRJOBS
    INNER JOIN NBRBJOB
        ON NBRBJOB_PIDM = NBRJOBS_PIDM
        AND NBRBJOB_POSN = NBRJOBS_POSN
		AND NBRBJOB_CONTRACT_TYPE = 'P'
		AND (NBRBJOB_BEGIN_DATE <= SYSDATE 
			AND (NBRBJOB_END_DATE > SYSDATE 
				OR NBRBJOB_END_DATE IS NULL))
    INNER JOIN SPRIDEN
        ON SPRIDEN_PIDM = NBRJOBS_PIDM
        AND SPRIDEN_CHANGE_IND IS NULL
    INNER JOIN PEBEMPL
        ON PEBEMPL_PIDM = NBRJOBS_PIDM
        AND PEBEMPL_EMPL_STATUS <> 'T'
        AND PEBEMPL_INTERNAL_FT_PT_IND <> 'P'
    WHERE NBRJOBS_STATUS = 'A'
    AND NBRJOBS_EFFECTIVE_DATE <= SYSDATE
	AND NBRJOBS_ECLS_CODE NOT IN ('E2','F3','H2','H4','N2','R0','R2','R4','R6')
    AND NBRJOBS_ORGN_CODE_TS NOT IN ('11001','11021','20023','20026','22129','22226','24209',
            '25008','25914','26050','26414','26510','29002','29003','29007','29011','29012',
            '29013','29304','29310','29311','30204','30205','30206','30209','30210','30212',
            '30232','30249','30251','30254','30257','30258','30501','30601','40017','52002',
            '52005','52006','52109','52201','52302','52303','53110','53701','54011','80010',
            '90011','90012','90016','95102','95113','95401','95601','96021','96031','96041',
            '96051','96061','97021','97031','97041','97051','97061','97071','97081','97091','97101')
    AND UPPER(NBRJOBS_DESC) NOT LIKE '%ADJUNCT%' 
    AND UPPER(NBRJOBS_DESC) NOT LIKE '%ADJCT%'
	AND (UPPER(NBRJOBS_DESC) LIKE UPPER('%EXECUTIVE%ASST%')
        OR UPPER(NBRJOBS_DESC) LIKE UPPER('%EXECUTIVE%ASSISTANT%'))
),
EXECUTIVE_ASSISTANTS AS (
    SELECT 'EXECUTIVE ASSISTANTS' TITLE, RAW_EXECUTIVE_ASSISTANTS.* FROM RAW_EXECUTIVE_ASSISTANTS
    WHERE RAW_EXECUTIVE_ASSISTANTS.NBRJOBS_EFFECTIVE_DATE = (SELECT MAX(NBRJOBS_EFFECTIVE_DATE) 
                                                    FROM RAW_EXECUTIVE_ASSISTANTS A 
                                                    WHERE A.NBRJOBS_PIDM = RAW_EXECUTIVE_ASSISTANTS.NBRJOBS_PIDM
                                                    AND A.NBRJOBS_POSN = RAW_EXECUTIVE_ASSISTANTS.NBRJOBS_POSN)
),
RAW_ASSISTANTS AS (
    SELECT SPRIDEN_LAST_NAME, SPRIDEN_MI, SPRIDEN_FIRST_NAME, SPRIDEN_ID, NBRJOBS.*, NBRBJOB.* FROM NBRJOBS
    INNER JOIN NBRBJOB
        ON NBRBJOB_PIDM = NBRJOBS_PIDM
        AND NBRBJOB_POSN = NBRJOBS_POSN
		AND NBRBJOB_CONTRACT_TYPE = 'P'
		AND (NBRBJOB_BEGIN_DATE <= SYSDATE 
			AND (NBRBJOB_END_DATE > SYSDATE 
				OR NBRBJOB_END_DATE IS NULL))
    INNER JOIN SPRIDEN
        ON SPRIDEN_PIDM = NBRJOBS_PIDM
        AND SPRIDEN_CHANGE_IND IS NULL
    INNER JOIN PEBEMPL
        ON PEBEMPL_PIDM = NBRJOBS_PIDM
        AND PEBEMPL_EMPL_STATUS <> 'T'
        AND PEBEMPL_INTERNAL_FT_PT_IND <> 'P'
    WHERE NBRJOBS_STATUS = 'A'
    AND NBRJOBS_EFFECTIVE_DATE <= SYSDATE
	AND NBRJOBS_ECLS_CODE NOT IN ('E2','F3','H2','H4','N2','R0','R2','R4','R6')
    AND NBRJOBS_ORGN_CODE_TS NOT IN ('11001','11021','20023','20026','22129','22226','24209',
            '25008','25914','26050','26414','26510','29002','29003','29007','29011','29012',
            '29013','29304','29310','29311','30204','30205','30206','30209','30210','30212',
            '30232','30249','30251','30254','30257','30258','30501','30601','40017','52002',
            '52005','52006','52109','52201','52302','52303','53110','53701','54011','80010',
            '90011','90012','90016','95102','95113','95401','95601','96021','96031','96041',
            '96051','96061','97021','97031','97041','97051','97061','97071','97081','97091','97101')
    AND UPPER(NBRJOBS_DESC) NOT LIKE '%ADJUNCT%' 
    AND UPPER(NBRJOBS_DESC) NOT LIKE '%ADJCT%'
	AND (UPPER(NBRJOBS_DESC) LIKE UPPER('%Asst To Dean%'))
),
ASSISTANTS AS (
    SELECT 'DEAN ASSISTANTS' TITLE, RAW_ASSISTANTS.* FROM RAW_ASSISTANTS
    WHERE RAW_ASSISTANTS.NBRJOBS_EFFECTIVE_DATE = (SELECT MAX(NBRJOBS_EFFECTIVE_DATE) 
                                                    FROM RAW_ASSISTANTS A 
                                                    WHERE A.NBRJOBS_PIDM = RAW_ASSISTANTS.NBRJOBS_PIDM
                                                    AND A.NBRJOBS_POSN = RAW_ASSISTANTS.NBRJOBS_POSN)
),
RAW_ADMIN AS (
    SELECT SPRIDEN_LAST_NAME, SPRIDEN_MI, SPRIDEN_FIRST_NAME, SPRIDEN_ID, NBRJOBS.*, NBRBJOB.* FROM NBRJOBS
    INNER JOIN NBRBJOB
        ON NBRBJOB_PIDM = NBRJOBS_PIDM
        AND NBRBJOB_POSN = NBRJOBS_POSN
		AND NBRBJOB_CONTRACT_TYPE = 'P'
		AND (NBRBJOB_BEGIN_DATE <= SYSDATE 
			AND (NBRBJOB_END_DATE > SYSDATE 
				OR NBRBJOB_END_DATE IS NULL))
    INNER JOIN SPRIDEN
        ON SPRIDEN_PIDM = NBRJOBS_PIDM
        AND SPRIDEN_CHANGE_IND IS NULL
    INNER JOIN PEBEMPL
        ON PEBEMPL_PIDM = NBRJOBS_PIDM
        AND PEBEMPL_EMPL_STATUS <> 'T'
        AND PEBEMPL_INTERNAL_FT_PT_IND <> 'P'
    WHERE NBRJOBS_STATUS = 'A'
    AND NBRJOBS_EFFECTIVE_DATE <= SYSDATE
	AND NBRJOBS_ECLS_CODE NOT IN ('E2','F3','H2','H4','N2','R0','R2','R4','R6')
    AND NBRJOBS_ORGN_CODE_TS NOT IN ('11001','11021','20023','20026','22129','22226','24209',
            '25008','25914','26050','26414','26510','29002','29003','29007','29011','29012',
            '29013','29304','29310','29311','30204','30205','30206','30209','30210','30212',
            '30232','30249','30251','30254','30257','30258','30501','30601','40017','52002',
            '52005','52006','52109','52201','52302','52303','53110','53701','54011','80010',
            '90011','90012','90016','95102','95113','95401','95601','96021','96031','96041',
            '96051','96061','97021','97031','97041','97051','97061','97071','97081','97091','97101')
    AND UPPER(NBRJOBS_DESC) NOT LIKE '%ADJUNCT%' 
    AND UPPER(NBRJOBS_DESC) NOT LIKE '%ADJCT%'
	AND LOWER(NBRJOBS_DESC) LIKE '%asst admin%'
),
ADMIN AS (
    SELECT 'ADMIN ASSISTANTS' TITLE, RAW_ADMIN.* FROM RAW_ADMIN
    WHERE RAW_ADMIN.NBRJOBS_EFFECTIVE_DATE = (SELECT MAX(NBRJOBS_EFFECTIVE_DATE) FROM RAW_ADMIN A
                                                WHERE RAW_ADMIN.NBRJOBS_PIDM = A.NBRJOBS_PIDM
                                                AND RAW_ADMIN.NBRJOBS_POSN = A.NBRJOBS_POSN)
),
RACES AS (
    SELECT GORPRAC_PIDM,
        LISTAGG((CASE GORPRAC_RACE_CDE WHEN '4' THEN 'AMERICAN_INDIAN_ALASKA_NATIVE'
                WHEN '5' THEN 'ASIAN'
                WHEN '6' THEN 'BLACK_AFRICAN_AMERICAN'
                WHEN '7' THEN 'NATIVE_HAWAIIAN_PACIFIC_ISLANDER'
                WHEN '8' THEN 'WHITE'
                ELSE ' ' END), ' ')
        WITHIN GROUP (
            ORDER BY GORPRAC_RACE_CDE
        ) AS RACE
    FROM GORPRAC
    GROUP BY GORPRAC_PIDM
    ORDER BY GORPRAC_PIDM
),
PEOPLE AS (
    SELECT PRESIDENT.TITLE TITLE,
        PRESIDENT.SPRIDEN_FIRST_NAME FIRST_NAME,
        NVL(PRESIDENT.SPRIDEN_MI, ' ') MIDDLE_NAME,
        PRESIDENT.SPRIDEN_LAST_NAME LAST_NAME,
        NVL((SELECT SPBPERS_NAME_PREFIX FROM SPBPERS WHERE SPBPERS_PIDM = PRESIDENT.NBRJOBS_PIDM), ' ') PREFIX,
        NVL((SELECT SPBPERS_NAME_SUFFIX FROM SPBPERS WHERE SPBPERS_PIDM = PRESIDENT.NBRJOBS_PIDM), ' ') SUFFIX,
        'Yes' ACTIVE,
        PRESIDENT.SPRIDEN_ID EMPLOYEE_ID,
        NVL((SELECT GOREMAL_EMAIL_ADDRESS FROM GOREMAL WHERE GOREMAL_PIDM = PRESIDENT.NBRJOBS_PIDM AND lower(GOREMAL_EMAIL_ADDRESS) LIKE '%@sfasu.edu' AND GOREMAL_PREFERRED_IND = 'Y'), ' ') EMAIL,
        NVL((SELECT GOBTPAC_EXTERNAL_USER FROM gobtpac WHERE GOBTPAC_PIDM = PRESIDENT.NBRJOBS_PIDM), ' ') USERNAME,
        ' ' NIH_COMMONS_ID,
        ' ' NSF_ID,
        ' ' NASA_NSPIRES_ID,
        ' ' ORCID_ID,
        ' ' DEGREE_DESCRIPTION,
        ' ' DEGREE_YEAR,
        ' ' DEGREE_QUALIFICATIONS,	
        (CASE (SELECT UPPER(SPBPERS_SEX) FROM SPBPERS WHERE SPBPERS_PIDM = PRESIDENT.NBRJOBS_PIDM) WHEN 'F' THEN 'FEMALE'
            WHEN 'M' THEN 'MALE'
            ELSE ' ' END) AS GENDER,
        (CASE (SELECT SPBPERS_ETHN_CDE FROM SPBPERS WHERE SPBPERS_PIDM = PRESIDENT.NBRJOBS_PIDM) WHEN '1' THEN 'NOT_HISPANIC'
            WHEN '2' THEN 'HISPANIC'
            ELSE ' ' END) AS ETHNICITY,
        NVL((SELECT RACE FROM RACES WHERE RACES.GORPRAC_PIDM = PRESIDENT.NBRJOBS_PIDM), ' ') RACES,
        ' ' DISABILITIES,
        NVL((SELECT SPBPERS_CITZ_IND FROM SPBPERS WHERE SPBPERS_PIDM = PRESIDENT.NBRJOBS_PIDM), 'US_CITIZEN') CITIZENSHIP,
        ' ' PHONE,
        ' ' FAX,
        '1936 North Street' STREET_1,
        ' ' STREET_2,
        'United States of America' COUNTRY,
        'Texas' STATE_PROVINCE,
        'Nacogdoches' COUNTY,
        'Nacogdoches' CITY,
        '75962-3940' POSTAL_CODE,
        'Yes' CREATE_ACCOUNT
    FROM PRESIDENT
    UNION 
    SELECT VP.TITLE TITLE,
        VP.SPRIDEN_FIRST_NAME FIRST_NAME,
        NVL(VP.SPRIDEN_MI, ' ') MIDDLE_NAME,
        VP.SPRIDEN_LAST_NAME LAST_NAME,
        NVL((SELECT SPBPERS_NAME_PREFIX FROM SPBPERS WHERE SPBPERS_PIDM = VP.NBRJOBS_PIDM), ' ') PREFIX,
        NVL((SELECT SPBPERS_NAME_SUFFIX FROM SPBPERS WHERE SPBPERS_PIDM = VP.NBRJOBS_PIDM), ' ') SUFFIX,
        'Yes' ACTIVE,
        VP.SPRIDEN_ID EMPLOYEE_ID,
        NVL((SELECT GOREMAL_EMAIL_ADDRESS FROM GOREMAL WHERE GOREMAL_PIDM = VP.NBRJOBS_PIDM AND lower(GOREMAL_EMAIL_ADDRESS) LIKE '%@sfasu.edu' AND GOREMAL_PREFERRED_IND = 'Y'), ' ') EMAIL,
        NVL((SELECT GOBTPAC_EXTERNAL_USER FROM gobtpac WHERE GOBTPAC_PIDM = VP.NBRJOBS_PIDM), ' ') USERNAME,
        ' ' NIH_COMMONS_ID,
        ' ' NSF_ID,
        ' ' NASA_NSPIRES_ID,
        ' ' ORCID_ID,
        ' ' DEGREE_DESCRIPTION,
        ' ' DEGREE_YEAR,
        ' ' DEGREE_QUALIFICATIONS,	
        (CASE (SELECT UPPER(SPBPERS_SEX) FROM SPBPERS WHERE SPBPERS_PIDM = VP.NBRJOBS_PIDM) WHEN 'F' THEN 'FEMALE'
            WHEN 'M' THEN 'MALE'
            ELSE ' ' END) AS GENDER,
        (CASE (SELECT SPBPERS_ETHN_CDE FROM SPBPERS WHERE SPBPERS_PIDM = VP.NBRJOBS_PIDM) WHEN '1' THEN 'NOT_HISPANIC'
            WHEN '2' THEN 'HISPANIC'
            ELSE ' ' END) AS ETHNICITY,
        NVL((SELECT RACE FROM RACES WHERE RACES.GORPRAC_PIDM = VP.NBRJOBS_PIDM), ' ') RACES,
        ' ' DISABILITIES,
        NVL((SELECT SPBPERS_CITZ_IND FROM SPBPERS WHERE SPBPERS_PIDM = VP.NBRJOBS_PIDM), 'US_CITIZEN') CITIZENSHIP,
        ' ' PHONE,
        ' ' FAX,
        '1936 North Street' STREET_1,
        ' ' STREET_2,
        'United States of America' COUNTRY,
        'Texas' STATE_PROVINCE,
        'Nacogdoches' COUNTY,
        'Nacogdoches' CITY,
        '75962-3940' POSTAL_CODE,
        'Yes' CREATE_ACCOUNT
    FROM VP
    UNION
    SELECT PROVOST.TITLE TITLE,
        PROVOST.SPRIDEN_FIRST_NAME FIRST_NAME,
        NVL(PROVOST.SPRIDEN_MI, ' ') MIDDLE_NAME,
        PROVOST.SPRIDEN_LAST_NAME LAST_NAME,
        NVL((SELECT SPBPERS_NAME_PREFIX FROM SPBPERS WHERE SPBPERS_PIDM = PROVOST.NBRJOBS_PIDM), ' ') PREFIX,
        NVL((SELECT SPBPERS_NAME_SUFFIX FROM SPBPERS WHERE SPBPERS_PIDM = PROVOST.NBRJOBS_PIDM), ' ') SUFFIX,
        'Yes' ACTIVE,
        PROVOST.SPRIDEN_ID EMPLOYEE_ID,
        NVL((SELECT GOREMAL_EMAIL_ADDRESS FROM GOREMAL WHERE GOREMAL_PIDM = PROVOST.NBRJOBS_PIDM AND lower(GOREMAL_EMAIL_ADDRESS) LIKE '%@sfasu.edu' AND GOREMAL_PREFERRED_IND = 'Y'), ' ') EMAIL,
        NVL((SELECT GOBTPAC_EXTERNAL_USER FROM gobtpac WHERE GOBTPAC_PIDM = PROVOST.NBRJOBS_PIDM), ' ') USERNAME,
        ' ' NIH_COMMONS_ID,
        ' ' NSF_ID,
        ' ' NASA_NSPIRES_ID,
        ' ' ORCID_ID,
        ' ' DEGREE_DESCRIPTION,
        ' ' DEGREE_YEAR,
        ' ' DEGREE_QUALIFICATIONS,	
        (CASE (SELECT UPPER(SPBPERS_SEX) FROM SPBPERS WHERE SPBPERS_PIDM = PROVOST.NBRJOBS_PIDM) WHEN 'F' THEN 'FEMALE'
            WHEN 'M' THEN 'MALE'
            ELSE ' ' END) AS GENDER,
        (CASE (SELECT SPBPERS_ETHN_CDE FROM SPBPERS WHERE SPBPERS_PIDM = PROVOST.NBRJOBS_PIDM) WHEN '1' THEN 'NOT_HISPANIC'
            WHEN '2' THEN 'HISPANIC'
            ELSE ' ' END) AS ETHNICITY,
        NVL((SELECT RACE FROM RACES WHERE RACES.GORPRAC_PIDM = PROVOST.NBRJOBS_PIDM), ' ') RACES,
        ' ' DISABILITIES,
        NVL((SELECT SPBPERS_CITZ_IND FROM SPBPERS WHERE SPBPERS_PIDM = PROVOST.NBRJOBS_PIDM), 'US_CITIZEN') CITIZENSHIP,
        ' ' PHONE,
        ' ' FAX,
        '1936 North Street' STREET_1,
        ' ' STREET_2,
        'United States of America' COUNTRY,
        'Texas' STATE_PROVINCE,
        'Nacogdoches' COUNTY,
        'Nacogdoches' CITY,
        '75962-3940' POSTAL_CODE,
        'Yes' CREATE_ACCOUNT
    FROM PROVOST
    UNION
    SELECT DIRECTORS.TITLE TITLE,
        DIRECTORS.SPRIDEN_FIRST_NAME FIRST_NAME,
        NVL(DIRECTORS.SPRIDEN_MI, ' ') MIDDLE_NAME,
        DIRECTORS.SPRIDEN_LAST_NAME LAST_NAME,
        NVL((SELECT SPBPERS_NAME_PREFIX FROM SPBPERS WHERE SPBPERS_PIDM = DIRECTORS.NBRJOBS_PIDM), ' ') PREFIX,
        NVL((SELECT SPBPERS_NAME_SUFFIX FROM SPBPERS WHERE SPBPERS_PIDM = DIRECTORS.NBRJOBS_PIDM), ' ') SUFFIX,
        'Yes' ACTIVE,
        DIRECTORS.SPRIDEN_ID EMPLOYEE_ID,
        NVL((SELECT GOREMAL_EMAIL_ADDRESS FROM GOREMAL WHERE GOREMAL_PIDM = DIRECTORS.NBRJOBS_PIDM AND lower(GOREMAL_EMAIL_ADDRESS) LIKE '%@sfasu.edu' AND GOREMAL_PREFERRED_IND = 'Y'), ' ') EMAIL,
        NVL((SELECT GOBTPAC_EXTERNAL_USER FROM gobtpac WHERE GOBTPAC_PIDM = DIRECTORS.NBRJOBS_PIDM), ' ') USERNAME,
        ' ' NIH_COMMONS_ID,
        ' ' NSF_ID,
        ' ' NASA_NSPIRES_ID,
        ' ' ORCID_ID,
        ' ' DEGREE_DESCRIPTION,
        ' ' DEGREE_YEAR,
        ' ' DEGREE_QUALIFICATIONS,	
        (CASE (SELECT UPPER(SPBPERS_SEX) FROM SPBPERS WHERE SPBPERS_PIDM = DIRECTORS.NBRJOBS_PIDM) WHEN 'F' THEN 'FEMALE'
            WHEN 'M' THEN 'MALE'
            ELSE ' ' END) AS GENDER,
        (CASE (SELECT SPBPERS_ETHN_CDE FROM SPBPERS WHERE SPBPERS_PIDM = DIRECTORS.NBRJOBS_PIDM) WHEN '1' THEN 'NOT_HISPANIC'
            WHEN '2' THEN 'HISPANIC'
            ELSE ' ' END) AS ETHNICITY,
        NVL((SELECT RACE FROM RACES WHERE RACES.GORPRAC_PIDM = DIRECTORS.NBRJOBS_PIDM), ' ') RACES,
        ' ' DISABILITIES,
        NVL((SELECT SPBPERS_CITZ_IND FROM SPBPERS WHERE SPBPERS_PIDM = DIRECTORS.NBRJOBS_PIDM), 'US_CITIZEN') CITIZENSHIP,
        ' ' PHONE,
        ' ' FAX,
        '1936 North Street' STREET_1,
        ' ' STREET_2,
        'United States of America' COUNTRY,
        'Texas' STATE_PROVINCE,
        'Nacogdoches' COUNTY,
        'Nacogdoches' CITY,
        '75962-3940' POSTAL_CODE,
        'Yes' CREATE_ACCOUNT
    FROM DIRECTORS
    UNION
    SELECT ACADEMIC_SU.TITLE,
        ACADEMIC_SU.SPRIDEN_FIRST_NAME FIRST_NAME,
        NVL(ACADEMIC_SU.SPRIDEN_MI, ' ') MIDDLE_NAME,
        ACADEMIC_SU.SPRIDEN_LAST_NAME LAST_NAME,
        NVL((SELECT SPBPERS_NAME_PREFIX FROM SPBPERS WHERE SPBPERS_PIDM = ACADEMIC_SU.NBRJOBS_PIDM), ' ') PREFIX,
        NVL((SELECT SPBPERS_NAME_SUFFIX FROM SPBPERS WHERE SPBPERS_PIDM = ACADEMIC_SU.NBRJOBS_PIDM), ' ') SUFFIX,
        'Yes' ACTIVE,
        ACADEMIC_SU.SPRIDEN_ID EMPLOYEE_ID,
        NVL((SELECT GOREMAL_EMAIL_ADDRESS FROM GOREMAL WHERE GOREMAL_PIDM = ACADEMIC_SU.NBRJOBS_PIDM AND lower(GOREMAL_EMAIL_ADDRESS) LIKE '%@sfasu.edu' AND GOREMAL_PREFERRED_IND = 'Y'), ' ') EMAIL,
        NVL((SELECT GOBTPAC_EXTERNAL_USER FROM gobtpac WHERE GOBTPAC_PIDM = ACADEMIC_SU.NBRJOBS_PIDM), ' ') USERNAME,
        ' ' NIH_COMMONS_ID,
        ' ' NSF_ID,
        ' ' NASA_NSPIRES_ID,
        ' ' ORCID_ID,
        ' ' DEGREE_DESCRIPTION,
        ' ' DEGREE_YEAR,
        ' ' DEGREE_QUALIFICATIONS,	
        (CASE (SELECT UPPER(SPBPERS_SEX) FROM SPBPERS WHERE SPBPERS_PIDM = ACADEMIC_SU.NBRJOBS_PIDM) WHEN 'F' THEN 'FEMALE'
            WHEN 'M' THEN 'MALE'
            ELSE ' ' END) AS GENDER,
        (CASE (SELECT SPBPERS_ETHN_CDE FROM SPBPERS WHERE SPBPERS_PIDM = ACADEMIC_SU.NBRJOBS_PIDM) WHEN '1' THEN 'NOT_HISPANIC'
            WHEN '2' THEN 'HISPANIC'
            ELSE ' ' END) AS ETHNICITY,
        NVL((SELECT RACE FROM RACES WHERE RACES.GORPRAC_PIDM = ACADEMIC_SU.NBRJOBS_PIDM), ' ') RACES,
        ' ' DISABILITIES,
        NVL((SELECT SPBPERS_CITZ_IND FROM SPBPERS WHERE SPBPERS_PIDM = ACADEMIC_SU.NBRJOBS_PIDM), 'US_CITIZEN') CITIZENSHIP,
        ' ' PHONE,
        ' ' FAX,
        '1936 North Street' STREET_1,
        ' ' STREET_2,
        'United States of America' COUNTRY,
        'Texas' STATE_PROVINCE,
        'Nacogdoches' COUNTY,
        'Nacogdoches' CITY,
        '75962-3940' POSTAL_CODE,
        'Yes' CREATE_ACCOUNT
    FROM ACADEMIC_SU
    UNION
    SELECT FACULTY.TITLE TITLE,
        FACULTY.SPRIDEN_FIRST_NAME FIRST_NAME,
        NVL(FACULTY.SPRIDEN_MI, ' ') MIDDLE_NAME,
        FACULTY.SPRIDEN_LAST_NAME LAST_NAME,
        NVL((SELECT SPBPERS_NAME_PREFIX FROM SPBPERS WHERE SPBPERS_PIDM = FACULTY.NBRJOBS_PIDM), ' ') PREFIX,
        NVL((SELECT SPBPERS_NAME_SUFFIX FROM SPBPERS WHERE SPBPERS_PIDM = FACULTY.NBRJOBS_PIDM), ' ') SUFFIX,
        'Yes' ACTIVE,
        FACULTY.SPRIDEN_ID EMPLOYEE_ID,
        NVL((SELECT GOREMAL_EMAIL_ADDRESS FROM GOREMAL WHERE GOREMAL_PIDM = FACULTY.NBRJOBS_PIDM AND lower(GOREMAL_EMAIL_ADDRESS) LIKE '%@sfasu.edu' AND GOREMAL_PREFERRED_IND = 'Y'), ' ') EMAIL,
        NVL((SELECT GOBTPAC_EXTERNAL_USER FROM gobtpac WHERE GOBTPAC_PIDM = FACULTY.NBRJOBS_PIDM), ' ') USERNAME,
        ' ' NIH_COMMONS_ID,
        ' ' NSF_ID,
        ' ' NASA_NSPIRES_ID,
        ' ' ORCID_ID,
        ' ' DEGREE_DESCRIPTION,
        ' ' DEGREE_YEAR,
        ' ' DEGREE_QUALIFICATIONS,	
        (CASE (SELECT UPPER(SPBPERS_SEX) FROM SPBPERS WHERE SPBPERS_PIDM = FACULTY.NBRJOBS_PIDM) WHEN 'F' THEN 'FEMALE'
            WHEN 'M' THEN 'MALE'
            ELSE ' ' END) AS GENDER,
        (CASE (SELECT SPBPERS_ETHN_CDE FROM SPBPERS WHERE SPBPERS_PIDM = FACULTY.NBRJOBS_PIDM) WHEN '1' THEN 'NOT_HISPANIC'
            WHEN '2' THEN 'HISPANIC'
            ELSE ' ' END) AS ETHNICITY,
        NVL((SELECT RACE FROM RACES WHERE RACES.GORPRAC_PIDM = FACULTY.NBRJOBS_PIDM), ' ') RACES,
        ' ' DISABILITIES,
        NVL((SELECT SPBPERS_CITZ_IND FROM SPBPERS WHERE SPBPERS_PIDM = FACULTY.NBRJOBS_PIDM), 'US_CITIZEN') CITIZENSHIP,
        ' ' PHONE,
        ' ' FAX,
        '1936 North Street' STREET_1,
        ' ' STREET_2,
        'United States of America' COUNTRY,
        'Texas' STATE_PROVINCE,
        'Nacogdoches' COUNTY,
        'Nacogdoches' CITY,
        '75962-3940' POSTAL_CODE,
        'Yes' CREATE_ACCOUNT
    FROM FACULTY
    UNION
    SELECT EMPLOYEE.TITLE TITLE,
        EMPLOYEE.SPRIDEN_FIRST_NAME FIRST_NAME,
        NVL(EMPLOYEE.SPRIDEN_MI, ' ') MIDDLE_NAME,
        EMPLOYEE.SPRIDEN_LAST_NAME LAST_NAME,
        NVL((SELECT SPBPERS_NAME_PREFIX FROM SPBPERS WHERE SPBPERS_PIDM = EMPLOYEE.NBRJOBS_PIDM), ' ') PREFIX,
        NVL((SELECT SPBPERS_NAME_SUFFIX FROM SPBPERS WHERE SPBPERS_PIDM = EMPLOYEE.NBRJOBS_PIDM), ' ') SUFFIX,
        'Yes' ACTIVE,
        EMPLOYEE.SPRIDEN_ID EMPLOYEE_ID,
        NVL((SELECT GOREMAL_EMAIL_ADDRESS FROM GOREMAL WHERE GOREMAL_PIDM = EMPLOYEE.NBRJOBS_PIDM AND lower(GOREMAL_EMAIL_ADDRESS) LIKE '%@sfasu.edu' AND GOREMAL_PREFERRED_IND = 'Y'), ' ') EMAIL,
        NVL((SELECT GOBTPAC_EXTERNAL_USER FROM gobtpac WHERE GOBTPAC_PIDM = EMPLOYEE.NBRJOBS_PIDM), ' ') USERNAME,
        ' ' NIH_COMMONS_ID,
        ' ' NSF_ID,
        ' ' NASA_NSPIRES_ID,
        ' ' ORCID_ID,
        ' ' DEGREE_DESCRIPTION,
        ' ' DEGREE_YEAR,
        ' ' DEGREE_QUALIFICATIONS,	
        (CASE (SELECT UPPER(SPBPERS_SEX) FROM SPBPERS WHERE SPBPERS_PIDM = EMPLOYEE.NBRJOBS_PIDM) WHEN 'F' THEN 'FEMALE'
            WHEN 'M' THEN 'MALE'
            ELSE ' ' END) AS GENDER,
        (CASE (SELECT SPBPERS_ETHN_CDE FROM SPBPERS WHERE SPBPERS_PIDM = EMPLOYEE.NBRJOBS_PIDM) WHEN '1' THEN 'NOT_HISPANIC'
            WHEN '2' THEN 'HISPANIC'
            ELSE ' ' END) AS ETHNICITY,
        NVL((SELECT RACE FROM RACES WHERE RACES.GORPRAC_PIDM = EMPLOYEE.NBRJOBS_PIDM), ' ') RACES,
        ' ' DISABILITIES,
        NVL((SELECT SPBPERS_CITZ_IND FROM SPBPERS WHERE SPBPERS_PIDM = EMPLOYEE.NBRJOBS_PIDM), 'US_CITIZEN') CITIZENSHIP,
        ' ' PHONE,
        ' ' FAX,
        '1936 North Street' STREET_1,
        ' ' STREET_2,
        'United States of America' COUNTRY,
        'Texas' STATE_PROVINCE,
        'Nacogdoches' COUNTY,
        'Nacogdoches' CITY,
        '75962-3940' POSTAL_CODE,
        'Yes' CREATE_ACCOUNT
    FROM EMPLOYEE
    UNION
    SELECT EXECUTIVE_ASSISTANTS.TITLE TITLE,
        EXECUTIVE_ASSISTANTS.SPRIDEN_FIRST_NAME FIRST_NAME,
        NVL(EXECUTIVE_ASSISTANTS.SPRIDEN_MI, ' ') MIDDLE_NAME,
        EXECUTIVE_ASSISTANTS.SPRIDEN_LAST_NAME LAST_NAME,
        NVL((SELECT SPBPERS_NAME_PREFIX FROM SPBPERS WHERE SPBPERS_PIDM = EXECUTIVE_ASSISTANTS.NBRJOBS_PIDM), ' ') PREFIX,
        NVL((SELECT SPBPERS_NAME_SUFFIX FROM SPBPERS WHERE SPBPERS_PIDM = EXECUTIVE_ASSISTANTS.NBRJOBS_PIDM), ' ') SUFFIX,
        'Yes' ACTIVE,
        EXECUTIVE_ASSISTANTS.SPRIDEN_ID EMPLOYEE_ID,
        NVL((SELECT GOREMAL_EMAIL_ADDRESS FROM GOREMAL WHERE GOREMAL_PIDM = EXECUTIVE_ASSISTANTS.NBRJOBS_PIDM AND lower(GOREMAL_EMAIL_ADDRESS) LIKE '%@sfasu.edu' AND GOREMAL_PREFERRED_IND = 'Y'), ' ') EMAIL,
        NVL((SELECT GOBTPAC_EXTERNAL_USER FROM gobtpac WHERE GOBTPAC_PIDM = EXECUTIVE_ASSISTANTS.NBRJOBS_PIDM), ' ') USERNAME,
        ' ' NIH_COMMONS_ID,
        ' ' NSF_ID,
        ' ' NASA_NSPIRES_ID,
        ' ' ORCID_ID,
        ' ' DEGREE_DESCRIPTION,
        ' ' DEGREE_YEAR,
        ' ' DEGREE_QUALIFICATIONS,	
        (CASE (SELECT UPPER(SPBPERS_SEX) FROM SPBPERS WHERE SPBPERS_PIDM = EXECUTIVE_ASSISTANTS.NBRJOBS_PIDM) WHEN 'F' THEN 'FEMALE'
            WHEN 'M' THEN 'MALE'
            ELSE ' ' END) AS GENDER,
        (CASE (SELECT SPBPERS_ETHN_CDE FROM SPBPERS WHERE SPBPERS_PIDM = EXECUTIVE_ASSISTANTS.NBRJOBS_PIDM) WHEN '1' THEN 'NOT_HISPANIC'
            WHEN '2' THEN 'HISPANIC'
            ELSE ' ' END) AS ETHNICITY,
        NVL((SELECT RACE FROM RACES WHERE RACES.GORPRAC_PIDM = EXECUTIVE_ASSISTANTS.NBRJOBS_PIDM), ' ') RACES,
        ' ' DISABILITIES,
        NVL((SELECT SPBPERS_CITZ_IND FROM SPBPERS WHERE SPBPERS_PIDM = EXECUTIVE_ASSISTANTS.NBRJOBS_PIDM), 'US_CITIZEN') CITIZENSHIP,
        ' ' PHONE,
        ' ' FAX,
        '1936 North Street' STREET_1,
        ' ' STREET_2,
        'United States of America' COUNTRY,
        'Texas' STATE_PROVINCE,
        'Nacogdoches' COUNTY,
        'Nacogdoches' CITY,
        '75962-3940' POSTAL_CODE,
        'Yes' CREATE_ACCOUNT
    FROM EXECUTIVE_ASSISTANTS
    UNION
    SELECT ASSISTANTS.TITLE TITLE,
        ASSISTANTS.SPRIDEN_FIRST_NAME FIRST_NAME,
        NVL(ASSISTANTS.SPRIDEN_MI, ' ') MIDDLE_NAME,
        ASSISTANTS.SPRIDEN_LAST_NAME LAST_NAME,
        NVL((SELECT SPBPERS_NAME_PREFIX FROM SPBPERS WHERE SPBPERS_PIDM = ASSISTANTS.NBRJOBS_PIDM), ' ') PREFIX,
        NVL((SELECT SPBPERS_NAME_SUFFIX FROM SPBPERS WHERE SPBPERS_PIDM = ASSISTANTS.NBRJOBS_PIDM), ' ') SUFFIX,
        'Yes' ACTIVE,
        ASSISTANTS.SPRIDEN_ID EMPLOYEE_ID,
        NVL((SELECT GOREMAL_EMAIL_ADDRESS FROM GOREMAL WHERE GOREMAL_PIDM = ASSISTANTS.NBRJOBS_PIDM AND lower(GOREMAL_EMAIL_ADDRESS) LIKE '%@sfasu.edu' AND GOREMAL_PREFERRED_IND = 'Y'), ' ') EMAIL,
        NVL((SELECT GOBTPAC_EXTERNAL_USER FROM gobtpac WHERE GOBTPAC_PIDM = ASSISTANTS.NBRJOBS_PIDM), ' ') USERNAME,
        ' ' NIH_COMMONS_ID,
        ' ' NSF_ID,
        ' ' NASA_NSPIRES_ID,
        ' ' ORCID_ID,
        ' ' DEGREE_DESCRIPTION,
        ' ' DEGREE_YEAR,
        ' ' DEGREE_QUALIFICATIONS,	
        (CASE (SELECT UPPER(SPBPERS_SEX) FROM SPBPERS WHERE SPBPERS_PIDM = ASSISTANTS.NBRJOBS_PIDM) WHEN 'F' THEN 'FEMALE'
            WHEN 'M' THEN 'MALE'
            ELSE ' ' END) AS GENDER,
        (CASE (SELECT SPBPERS_ETHN_CDE FROM SPBPERS WHERE SPBPERS_PIDM = ASSISTANTS.NBRJOBS_PIDM) WHEN '1' THEN 'NOT_HISPANIC'
            WHEN '2' THEN 'HISPANIC'
            ELSE ' ' END) AS ETHNICITY,
        NVL((SELECT RACE FROM RACES WHERE RACES.GORPRAC_PIDM = ASSISTANTS.NBRJOBS_PIDM), ' ') RACES,
        ' ' DISABILITIES,
        NVL((SELECT SPBPERS_CITZ_IND FROM SPBPERS WHERE SPBPERS_PIDM = ASSISTANTS.NBRJOBS_PIDM), 'US_CITIZEN') CITIZENSHIP,
        ' ' PHONE,
        ' ' FAX,
        '1936 North Street' STREET_1,
        ' ' STREET_2,
        'United States of America' COUNTRY,
        'Texas' STATE_PROVINCE,
        'Nacogdoches' COUNTY,
        'Nacogdoches' CITY,
        '75962-3940' POSTAL_CODE,
        'Yes' CREATE_ACCOUNT
    FROM ASSISTANTS
    UNION
    SELECT ADMIN.TITLE TITLE,
        ADMIN.SPRIDEN_FIRST_NAME FIRST_NAME,
        NVL(ADMIN.SPRIDEN_MI, ' ') MIDDLE_NAME,
        ADMIN.SPRIDEN_LAST_NAME LAST_NAME,
        NVL((SELECT SPBPERS_NAME_PREFIX FROM SPBPERS WHERE SPBPERS_PIDM = ADMIN.NBRJOBS_PIDM), ' ') PREFIX,
        NVL((SELECT SPBPERS_NAME_SUFFIX FROM SPBPERS WHERE SPBPERS_PIDM = ADMIN.NBRJOBS_PIDM), ' ') SUFFIX,
        'Yes' ACTIVE,
        ADMIN.SPRIDEN_ID EMPLOYEE_ID,
        NVL((SELECT GOREMAL_EMAIL_ADDRESS FROM GOREMAL WHERE GOREMAL_PIDM = ADMIN.NBRJOBS_PIDM AND lower(GOREMAL_EMAIL_ADDRESS) LIKE '%@sfasu.edu' AND GOREMAL_PREFERRED_IND = 'Y'), ' ') EMAIL,
        NVL((SELECT GOBTPAC_EXTERNAL_USER FROM gobtpac WHERE GOBTPAC_PIDM = ADMIN.NBRJOBS_PIDM), ' ') USERNAME,
        ' ' NIH_COMMONS_ID,
        ' ' NSF_ID,
        ' ' NASA_NSPIRES_ID,
        ' ' ORCID_ID,
        ' ' DEGREE_DESCRIPTION,
        ' ' DEGREE_YEAR,
        ' ' DEGREE_QUALIFICATIONS,	
        (CASE (SELECT UPPER(SPBPERS_SEX) FROM SPBPERS WHERE SPBPERS_PIDM = ADMIN.NBRJOBS_PIDM) WHEN 'F' THEN 'FEMALE'
            WHEN 'M' THEN 'MALE'
            ELSE ' ' END) AS GENDER,
        (CASE (SELECT SPBPERS_ETHN_CDE FROM SPBPERS WHERE SPBPERS_PIDM = ADMIN.NBRJOBS_PIDM) WHEN '1' THEN 'NOT_HISPANIC'
            WHEN '2' THEN 'HISPANIC'
            ELSE ' ' END) AS ETHNICITY,
        NVL((SELECT RACE FROM RACES WHERE RACES.GORPRAC_PIDM = ADMIN.NBRJOBS_PIDM), ' ') RACES,
        ' ' DISABILITIES,
        NVL((SELECT SPBPERS_CITZ_IND FROM SPBPERS WHERE SPBPERS_PIDM = ADMIN.NBRJOBS_PIDM), 'US_CITIZEN') CITIZENSHIP,
        ' ' PHONE,
        ' ' FAX,
        '1936 North Street' STREET_1,
        ' ' STREET_2,
        'United States of America' COUNTRY,
        'Texas' STATE_PROVINCE,
        'Nacogdoches' COUNTY,
        'Nacogdoches' CITY,
        '75962-3940' POSTAL_CODE,
        'Yes' CREATE_ACOUNT
    FROM ADMIN
),
POSNS as (
    SELECT distinct spriden_id,
      spriden_first_name,
      spriden_last_name,
      spriden_mi,
      pebempl_empl_status,
      pebempl_ecls_code,
      nbrbjob_posn,
      nbrjobs_status,
      nbrbjob_suff,
      nbrbjob_contract_type,
      nbrjobs_desc,
      nbrjobs_orgn_code_ts,
      (SELECT ftvorgn_title
        FROM ftvorgn
        WHERE a.nbrjobs_orgn_code_ts = ftvorgn_orgn_code
        AND FTVORGN_STATUS_IND       = 'A'
        AND FTVORGN_eff_DATE         =
            (SELECT MAX(FTVORGN_eff_DATE)
                FROM FTVORGN B
                WHERE B.FTVORGN_ORGN_CODE = a.nbrjobs_orgn_code_ts
                AND FTVORGN_STATUS_IND    = 'A')
      ) TS_ORGN_DESC,
      pebempl_orgn_code_home,
      (SELECT ftvorgn_title
      FROM ftvorgn
      WHERE FTVORGN_STATUS_IND   = 'A'
      AND pebempl_orgn_code_home = ftvorgn_orgn_code
      AND FTVORGN_eff_DATE       =
        (SELECT MAX(B.FTVORGN_eff_DATE)
        FROM FTVORGN B
        WHERE B.FTVORGN_ORGN_CODE = pebempl_orgn_code_home
        AND B.FTVORGN_STATUS_IND  = 'A'
        )
      ) HOME_ORGN_DESC,
      'Yes' PRIMARY_APPOINTMENT
    FROM spriden,
      nbrbjob,
      pebempl c,
      nbrjobs a
    WHERE nbrbjob_pidm           = spriden_pidm
    AND spriden_pidm             = pebempl_pidm
    AND nbrjobs_pidm             = pebempl_pidm
    AND nbrjobs_pidm             = nbrbjob_pidm
    AND nbrbjob_contract_type    = 'P'
    AND nbrjobs_status          != 'T'
    AND nbrbjob_posn             = nbrjobs_posn
    AND nbrbjob_suff             = nbrjobs_suff
    AND UPPER(NBRJOBS_DESC) NOT LIKE '%ADJUNCT%'
    AND UPPER(NBRJOBS_DESC) NOT LIKE '%JUNCT%'
    AND a.NBRJOBS_EFFECTIVE_DATE =
      (SELECT MAX(NBRJOBS_EFFECTIVE_DATE)
      FROM nbrjobs
      WHERE a.nbrjobs_pidm = nbrjobs_pidm
      AND nbrjobs_posn     = a.nbrjobs_posn
      AND nbrjobs_suff     = a.nbrjobs_suff
      AND nbrjobs_status  != 'T'
      )
    AND pebempl_empl_status                != 'T'
    AND pebempl_ecls_code                  != 'R0'
    AND spriden_change_ind                 IS NULL
    AND (NBRBJOB_END_DATE                  > SYSDATE
    OR NBRBJOB_END_DATE                    IS NULL)
    AND SPRIDEN_ID IN (SELECT DISTINCT PEOPLE.EMPLOYEE_ID FROM PEOPLE)
    union all
    SELECT distinct spriden_id,
      spriden_first_name,
      spriden_last_name,
      spriden_mi,
      pebempl_empl_status,
      pebempl_ecls_code,
      nbrbjob_posn,
      nbrjobs_status,
      nbrbjob_suff,
      nbrbjob_contract_type,
      nbrjobs_desc,
      nbrjobs_orgn_code_ts,
      (SELECT ftvorgn_title
      FROM ftvorgn
      WHERE a.nbrjobs_orgn_code_ts = ftvorgn_orgn_code
      AND FTVORGN_STATUS_IND       = 'A'
      AND FTVORGN_eff_DATE         =
        (SELECT MAX(FTVORGN_eff_DATE)
        FROM FTVORGN B
        WHERE B.FTVORGN_ORGN_CODE = a.nbrjobs_orgn_code_ts
        AND FTVORGN_STATUS_IND    = 'A'
        )
      ) TS_ORGN_DESC,
      pebempl_orgn_code_home,
      (SELECT ftvorgn_title
      FROM ftvorgn
      WHERE FTVORGN_STATUS_IND   = 'A'
      AND pebempl_orgn_code_home = ftvorgn_orgn_code
      AND FTVORGN_eff_DATE       =
        (SELECT MAX(B.FTVORGN_eff_DATE)
        FROM FTVORGN B
        WHERE B.FTVORGN_ORGN_CODE = pebempl_orgn_code_home
        AND B.FTVORGN_STATUS_IND  = 'A'
        )
      ) HOME_ORGN_DESC,
      'No' PRIMARY_APPOINTMENT
    FROM spriden,
      nbrbjob,
      pebempl c,
      nbrjobs a
    WHERE nbrbjob_pidm           = spriden_pidm
    AND spriden_pidm             = pebempl_pidm
    AND nbrjobs_pidm             = pebempl_pidm
    AND nbrjobs_pidm             = nbrbjob_pidm
    AND nbrbjob_contract_type    <> 'P'
    AND nbrjobs_status          != 'T'
    AND nbrbjob_posn             = nbrjobs_posn
    AND nbrbjob_suff             = nbrjobs_suff
    AND UPPER(NBRJOBS_DESC) NOT LIKE '%ADJUNCT%'
    AND UPPER(NBRJOBS_DESC) NOT LIKE '%JUNCT%'
    AND a.NBRJOBS_EFFECTIVE_DATE =
      (SELECT MAX(NBRJOBS_EFFECTIVE_DATE)
        FROM nbrjobs
          WHERE a.nbrjobs_pidm = nbrjobs_pidm
          AND nbrjobs_posn     = a.nbrjobs_posn
          AND nbrjobs_suff     = a.nbrjobs_suff
          AND nbrjobs_status  != 'T'
      )
    AND pebempl_empl_status                != 'T'
    AND pebempl_ecls_code                  != 'R0'
    AND spriden_change_ind                 IS NULL
    AND (NBRBJOB_END_DATE                  > SYSDATE
    OR NBRBJOB_END_DATE                    IS NULL)
    AND SPRIDEN_ID IN (SELECT DISTINCT PEOPLE.EMPLOYEE_ID FROM PEOPLE)
) 
SELECT DISTINCT NVL((SELECT GOBTPAC_EXTERNAL_USER FROM gobtpac WHERE GOBTPAC_PIDM = (SELECT SPRIDEN_PIDM FROM SPRIDEN WHERE SPRIDEN_ID = POSNS.SPRIDEN_ID AND SPRIDEN_CHANGE_IND IS NULL)), ' ') Username,
       POSNS.SPRIDEN_ID EmployeeID,
       (SELECT FTVORGN_FUND_CODE_DEF || '-' || POSNS.nbrjobs_orgn_code_ts 
        FROM FTVORGN 
        WHERE FTVORGN_ORGN_CODE = POSNS.nbrjobs_orgn_code_ts
        AND FTVORGN_EFF_DATE <= SYSDATE AND FTVORGN_NCHG_DATE > SYSDATE
        AND FTVORGN_STATUS_IND = 'A') UnitPrimaryCode,
       POSNS.TS_ORGN_DESC UnitName,
       POSNS.NBRJOBS_DESC Title,
       POSNS.PRIMARY_APPOINTMENT PrimaryAppointment,
       ' ' USGovernmentAgency,
       PEOPLE.EMAIL ContactEmail,
       ' ' ContactOfficePhone,
       ' ' ContactMobilePhone,
       ' ' ContactPager,
       ' ' ContactFax,
       'Email' ContactPrefferedContactMethod,
       PEOPLE.STREET_1 ContactStreet1,
       ' ' ContactStreet2,
       PEOPLE.COUNTY ContactCounty,
       PEOPLE.COUNTRY ContactCountry,
       PEOPLE.STATE_PROVINCE ContactState_Province,
       PEOPLE.CITY ContactCity,
       PEOPLE.POSTAL_CODE ContactPostalCode,
       ' ' ContactWebsite,
       '1936 North Street'||CHR(44)||' Nacogdoches'||CHR(44)||' TX 759062' PerformanceSiteOrganization,
       'Yes' PerformanceSiteActive,
       '073894727' PerformanceSiteDUNS,
       PEOPLE.EMAIL PerformanceSiteEmail,
       ' ' PerformanceSiteOfficePhone,
       ' ' PerformanceSiteMobilePhone,
       ' ' PerformanceSitePager,
       ' ' PerformanceSiteFax,
       'Email' PerformanceSitePreferredContactMethod,
       ' ' PerformanceSiteStreet1,
       ' ' PerformanceSiteStreet2,
       ' ' PerformanceSiteCounty,
       ' ' PerformanceSiteCountry,
       ' ' PerformanceSiteState_Province,
       ' ' PerformanceSiteCity,
       ' ' PerformanceSitePostalCode,
       ' ' PerformanceSiteWebsite,
       'TX-001' PerformanceSiteCongressionalDistrict,
       '12' CalendarMonths,
       ' ' CalendarSalary,
       '9' AcademicMonths,
       ' ' AcademicSalary,
       '3' SummerMonths,
       ' ' SummerSalary,
       'Y' PrincipalInvestigator,
       ' ' Assistant,
       ' ' AdministrationOfficial,
       ' ' SigningOfficial,
       ' ' Payee
FROM POSNS
LEFT JOIN PEOPLE
ON PEOPLE.EMPLOYEE_ID = POSNS.SPRIDEN_ID
ORDER BY POSNS.SPRIDEN_ID;
